feat(apit)!: added endpoint for batch source string editing.
crowdin/crowdin-api-client-php pull request #198
Opened 2024-11-13 15:59 UTC by DE-dylan-lauzon

Addresses issue #133

2024-11-14 08:27 UTC, andrii-bodnar requested changes
@DE-dylan-lauzon thank you for the contribution!

I just left a few comments, please address them.

2024-11-14 08:27 UTC, andrii-bodnar commented on src/CrowdinApiClient/Api/SourceStringApi.php
> +    public function batch(int $projectId, array $data)
```suggestion
    public function batchOperations(int $projectId, array $data)
```

2024-11-14 08:27 UTC, andrii-bodnar commented on src/CrowdinApiClient/Api/SourceStringApi.php
> +     * Batch Update Strings
```suggestion
     * String Batch Operations
```

2024-11-14 08:27 UTC, andrii-bodnar commented on src/CrowdinApiClient/Api/SourceStringApi.php
> +     * value $data[value] required object or string or bool.
```suggestion
     * value $data[value] required object, string, int, or bool
```

2024-11-14 08:27 UTC, andrii-bodnar commented on tests/CrowdinApiClient/Api/SourceStringApiTest.php
> +          fwrite(STDERR, print_r($batchResult->getData(), TRUE));
This is probably for debugging purposes only and should be removed

2024-11-14 08:27 UTC, andrii-bodnar commented on tests/CrowdinApiClient/Api/SourceStringApiTest.php
> +            'response' => '{
Please format this JSON properly

2024-11-14 15:45 UTC, andrii-bodnar commented
@DE-dylan-lauzon the CI has failed, please check the logs - https://github.com/crowdin/crowdin-api-client-php/actions/runs/11838764482/job/32990682687?pr=198

2024-11-14 15:59 UTC, DE-dylan-lauzon commented
Sorry about that. CS fixer caught a couple bits of whitespace that I missed. It passes locally, now.

2024-11-15 07:27 UTC, andrii-bodnar approved these changes
@DE-dylan-lauzon thank you!

2024-11-15 07:27 UTC, merged